### PR TITLE
Fix status bar not showing availability

### PR DESCRIPTION
**Pull request by charn**
Dividing with an integer always returned 0

**Broken**

broken

**Fixed**

fixed

### CODE REVIEW

**Comment by charn** [comment]
Mergy merge? :dancer:

**Comment by charn** [comment]
@eskerda Any chance to get this merged?

**Comment by eskerda** [comment]
@charn Sorry for the late response. Converting it to float to avoid running into a division by zero seems a counter-intuitive solution. It was probably related to some missing fields on the network. As of now, I think any issue causing it is fixed. I doublechecked the logic behind the slots spaghetti and it still makes sense.

**Comment by charn** [comment]
The problem in this case wasn't division by zero problem or a missing field. The problem is that the code works incorrectly on Python 2.x (which according to `setup.py` is supported) by expecting floating point results when performing division when using only integers. On Python 2.x if both operands are of type `int`, floor division is performed and an `int` is returned. If either operand is a `float`, classic division is performed and a `float` is returned.

Below is a simplified version of the issue that this PR would fix.

Python 2.7
```
>>> 1/2
0
>>> type(1/2)
<type 'int'>
```

Python 3.6
```
>>> 1/2
0.5
>>> type(1/2)
<class 'float'>
```

**Comment by eskerda** [comment]
@charn you are wiser than I am. Thanks for teaching me I must look more closely to the differences between python 2 and python 3.

Thank you for your contribution and sorry for dismissing this pull request!

**Pull request merged**
